config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "categories#index"
  resources :recipes, only: [:create, :new, :index, :show, :update, :edit, :destroy]
  resources :ingredients, only: [:create]
  resources :categories, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, dependent: :destroy
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes, through: :recipe_ingredients
  has_many :recipe_ingredients
  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipe_tags, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :tags, through: :recipe_tags
  has_many_attached :images
  belongs_to :category
  validates :category, presence: true
  validates :title, presence: true
  validates :main_ingredient, presence: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipes, through: :recipe_tags
  has_many :recipe_tags
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])

    if params[:tags].present?
      @selected_tags = Tag.where(id: params[:tags])
    else
      @selected_tags = []
    end

    @main_ingredient = params[:main_ingredient] if params[:main_ingredient].present?

  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @ingredient = Ingredient.new
  end

  def index
    @ingredients = Ingredient.all
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to @ingredient
    else
      render :new
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
  
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  def new
    @recipe_ingredient = RecipeIngredient.new
  end

  def index
    @recipe_ingredients = RecipeIngredient.all
  end

  def create
    @recipe_ingredient = RecipeIngredient.new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(parmas[:ingredient_id])
  end

end

app/controllers/recipe_tags_controller.rb
class RecipeTagsController < ApplicationController

  def new
    @recipe_tag = RecipeTag.new
  end

  def index
    @recipe_tags = RecipeTag.all
  end

  def create
    @recipe_tag = RecipeTag.new
    @recipe = Recipe.find(params[:recipe_id])
    @tag = Tag.find(params[:tag_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if params[:recipe][:recipe_ingredients].present?
      ingredients_list = params[:recipe][:recipe_ingredients].split(',').map(&:strip).map(&:downcase).uniq

      ingredients_list.each do |ingredient_name|
        ingredient = Ingredient.where('LOWER(name) = ?', ingredient_name.downcase).first_or_initialize
        ingredient.name = ingredient_name if ingredient.new_record?
        ingredient.save!
        @recipe.ingredients << ingredient
      end
    end

    if params[:tags].present?
      @recipe.tags = Tag.where(id: params[:tags])
    end

    if @recipe.save
      redirect_to recipes_path, notice: 'Recette créée avec succès'
    else
      render :new, status: :unprocessable_entity
    end
  end


  def index
    @recipes = Recipe.all.order('LOWER(title)')

    if params[:category].present?
      @selected_category = Category.find(params[:category])
      @recipes = @recipes.where(category_id: params[:category])
    else
      @selected_category = nil
    end

    @other_recipes = Recipe.none

    if params[:main_ingredient].present?
      searched_ingredient = params[:main_ingredient].downcase
      @main_ingredient = params[:main_ingredient]
      @recipes = @recipes.where("lower(main_ingredient) LIKE ?", "%#{searched_ingredient}%")
      @other_recipes = Recipe.joins(:ingredients)
        .where("lower(ingredients.name) LIKE ?", "%#{searched_ingredient}%")
        .where.not(id: @recipes.pluck(:id))
        .distinct
    end

    if params[:ingredients].present?
      @ingredients_list = Ingredient.where(id: params[:ingredients])
      @recipes = @recipes.joins(:ingredients).where(ingredients: { id: params[:ingredients] })
    else
      @ingredients_list = []
    end

    if params[:tags].present?
      @selected_tags = Tag.where(id: params[:tags])
      @recipes = @recipes.joins(:tags).where(tags: { id: params[:tags] })
    else
      @selected_tags = []
    end
  end

  def show
    @selected_category = @recipe.category
    @main_ingredient = @recipe.main_ingredient
    @ingredients_list = @recipe.ingredients
    @selected_tags = @recipe.tags
  end

  def edit
  end

  def update
    if params[:recipe][:recipe_ingredients].present?
      ingredients_list = params[:recipe][:recipe_ingredients].split(',').map(&:strip).map(&:downcase).uniq

      @recipe.ingredients.clear
      ingredients_list.each do |ingredient_name|
        ingredient = Ingredient.where('LOWER(name) = ?', ingredient_name).first_or_create(name: ingredient_name)
        @recipe.ingredients << ingredient
      end
    end

    if params[:tags].present?
      @recipe.tags = Tag.where(id: params[:tags])
    end

    if params[:remove_all_images] == "true"
      @recipe.images.purge
    end

    if @recipe.update(recipe_params.except(:images))
      if params[:recipe][:images].present?
        params[:recipe][:images].each do |image|
          @recipe.images.attach(image)
        end
      end
      redirect_to recipe_path(@recipe, return_to: params[:return_to]), notice: 'Recette mise à jour avec succès'
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @recipe.images.purge
    @recipe.destroy
    redirect_to recipes_path, status: :see_other, notice: "Recette supprimée avec succès"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :main_ingredient, :category_id, :source_url, images: [], tags: [])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipe_tags_helper.rb
module RecipeTagsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/index.html.erb
<div class="full-screen">
  <div class="container-custom">
    <h1 class="text-center">My Digital Coobook</h1>
    <hr class="thick-line">
    <div class="add-button-wrapper">
      <div class="add-button button-small">
        <%= link_to "Ajouter une recette", new_recipe_path %>
      </div>
    </div>
    <%= form_with url: recipes_path, method: :get, local: true, data: { turbo: false } do %>
      <div class="row-wrapper">
        <div class="row">
          <div class="col-6 col-lg-3 g-2">
            <div class="card-category category-selectable" data-category="0" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/id/1127070863/fr/photo/v%C3%A9g%C3%A9tarien-nems-vietnamiens-avec-carotte-concombre-sauce-%C3%A9pic%C3%A9e-nouilles-de-riz-et-de-choux.webp?a=1&b=1&s=612x612&w=0&k=20&c=IGPMUnAORlA4CosgTTUPi_vq5aiFyW-mEPR1lGQnJSc=)">
              <h2 class="text-size-regular color-white">Entrées</h2>
            </div>
          </div>
          <div class="col-6 col-lg-3 g-2">
            <div class="card-category category-selectable" data-category="1" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/id/488960908/fr/photo/de-p%C3%A2tes-maison.webp?a=1&b=1&s=612x612&w=0&k=20&c=t0rzgpw_8cFKmWRhroenw9B0S897AQdfNrUHhV2ijzA=)">
              <h2 class="text-size-regular color-white">Plats</h2>
            </div>
          </div>
          <div class="col-6 col-lg-3 g-2">
            <div class="card-category category-selectable" data-category="2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1499126167718-c87f5c1387e8?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHNhdWNlJTIwdmVyc2VyfGVufDB8fDB8fHww)">
              <h2 class="text-size-regular color-white">Sauces</h2>
            </div>
          </div>
          <div class="col-6 col-lg-3 g-2">
            <div class="card-category category-selectable" data-category="3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/id/1223139298/fr/photo/photographie-%C3%A0-angle-%C3%A9lev%C3%A9-dune-tarte-aux-fruits-en-treillis.webp?a=1&b=1&s=612x612&w=0&k=20&c=KHUwqNguKplwaf8cUWLOulB6uHlApfAlJDz8x_oeiNg=)">
              <h2 class="text-size-regular color-white">Desserts</h2>
            </div>
          </div>
        </div>
        <%= hidden_field_tag :category, params[:category], id: 'selected_category' %>
        <% if params[:category].present? %>
          <p>Selected category: <%= params[:category] %></p>
        <% end %>
      </div>
      <div class="d-flex flex-column justify-content-start">
        <div class="input-wrapper">
          <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Ingrédient : </h3></div>
          <label for="main_ingredient" class="d-none">Ingredient clé</label>
          <%= text_field_tag :main_ingredient, params[:main_ingredient], placeholder: "Carotte", class: "input-field text-size-small input-uppercase" %>
        </div>
        <div class="text-start padding-left-custom">
          <h3 class="form-label text-size-regular text-start">Tags (cliquez pour sélectionner) : </h3>
        </div>
        <div class="tag-wrapper">
          <% Tag.all.each do |tag| %>
            <div class="tag-item">
              <%= check_box_tag "tags[]", tag.id, params[:tags]&.include?(tag.id.to_s), id: "tag_#{tag.id}", class: "tag-checkbox" %>
              <%= label_tag "tag_#{tag.id}", tag.name, class: "tag-label" %>
            </div>
            <% end %>
        </div>
      </div>
      <div class="d-flex justify-content-center mt-2">
        <%= submit_tag "CHERCHER", class: "button-main" %>
      </div>
    <% end %>
    <div class="return-wrapper">
      <%= link_to "Déconnexion", destroy_user_session_path, 'data-turbo-method': :delete, class: "return-link", data: { confirm: 'Êtes-vous sûr de vouloir vous déconnecter ?' } %>
    </div>
  </div>
</div>

<script>
document.addEventListener("turbo:load", function() {
  const categoryCards = document.querySelectorAll(".category-selectable");
  const selectedCategoryField = document.getElementById("selected_category");

  categoryCards.forEach(card => {
    card.addEventListener("click", function() {
      const categoryId = this.getAttribute("data-category");
      selectedCategoryField.value = categoryId;
      categoryCards.forEach(c => c.classList.remove("category-selected"));
      this.classList.add("category-selected");
    });
  });
});
</script>

app/views/recipes/edit.html.erb
<div class="full-screen">
  <div class="container-custom">
      <%= form_with model: @recipe, url: recipe_path(@recipe), method: :patch, local: true, data: { turbo: false }, multipart: true do |f|  %>
        <div class="input-wrapper-low-padding input-wrapper-title">
          <label for="title" class="d-none">Titre</label>
          <%= f.text_field :title, placeholder: @recipe.title, value: @recipe.title, class: "input-field input-uppercase-italic" %>
        </div>
        <div class="d-flex flex-column align-items-center">
          <hr class="thick-line">
        </div>
        <div class="d-flex flex-column justify-content-start">
          <div class="input-wrapper-low-padding">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Catégorie : </h3></div>
            <label for="category" class="d-none">Catégorie</label>
              <%= f.select :category_id, options_for_select(Category.all.map { |c| [c.name, c.id] }, @recipe.category_id), class: "input-field text-size-small input-uppercase category-placeholder"%>
          </div>
          <div class="input-wrapper-low-padding">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Ingrédient clé : </h3></div>
            <label for="main_ingredient" class="d-none">Ingredient clé</label>
            <%= f.text_field :main_ingredient, placeholder: @recipe.main_ingredient, value: @recipe.main_ingredient, class: "input-field text-size-small input-uppercase-italic" %>
          </div>
          <div class="input-wrapper-column">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Autres ingrédients: </h3></div>
            <label for="recipe_ingredients" class="d-none">Autres ingrédients</label>
            <div class="input-container">
              <%= f.text_field :recipe_ingredients, value: @recipe.ingredients.map(&:name).join(', '), placeholder: "oignon, sauce soja, gingembre", class: "input-field text-size-small input-uppercase-italic" %>
            </div>
          </div>
          <div class="text-start padding-left-custom">
            <h3 class="form-label text-size-regular text-start">Tags (cliquez pour sélectionner) : </h3>
          </div>
          <div class="tag-wrapper">
              <% Tag.all.each do |tag| %>
                <div class="tag-item">
                  <%= check_box_tag "tags[]", tag.id, @recipe.tags.include?(tag), id: "tag_#{tag.id}", class: "tag-checkbox" %>
                  <%= label_tag "tag_#{tag.id}", tag.name, class: "tag-label" %>
                </div>
              <% end %>
          </div>
          <div class="input-wrapper-low-padding pb-0">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">URL : </h3></div>
            <label for="source_url" class="d-none">URL</label>
            <%= f.text_field :source_url, placeholder: @recipe.source_url, value: @recipe.source_url, class: "input-field text-size-small input-italic" %>
          </div>
          <div class="input-wrapper-low-padding d-flex flex-column align-items-start ">
            <div class="d-flex flex-row justify-content-center align-items-center me-2 mb-1">
              <h3 class="form-label text-size-regular text-start me-2">Photos (<%= @recipe.images.count %>) : </h3>
              <% if @recipe.images.any? %>
                <div class="delete-all-images">
                  <%= check_box_tag "remove_all_images", "true" %>
                  <%= label_tag "remove_all_images", "Supprimer les images" %>
                </div>
              <% end %>
            </div>
            <div class="d-flex flex-row align-items-center">
              <label for="recipe_images" class="form-label text-size-regular text-start me-2">Ajout photos : </label>
              <%= f.file_field :images, multiple: true, accept: "image/*", class: "input-field text-size-small lowercase-placeholder" %>
            </div>
          </div>
          <div class="d-flex justify-content-center mt-2">
            <%= f.submit "ENREGISTRER", class: "button-main" %>
          </div>
        </div>
      <% end %>
      <div class="destroy-link">
        <%= link_to "Supprimer la recette", recipe_path(@recipe), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette recette ?" }, class: "color-red text-size-xsmall " %>
      </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="full-screen">
  <div class="container-custom">
    <%= link_to "My Digital Coobook", categories_path, class: "text-center h1" %>
    <hr class="thick-line">
    <div class="input-wrapper py-1 mt-1">
      <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="form-label text-size-regular">Catégorie :</h3>
        <% if @selected_category.present? %>
          <h3 class="form-label text-size-regular color-green ms-2">
            <%= @selected_category.name.capitalize %>
          </h3>
        <% else %>
          <h3 class="form-label text-size-regular color-green ms-2">Toutes</h3>
        <% end %>
      </div>
    </div>
    <div class="input-wrapper py-1">
      <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="form-label text-size-regular">Ingrédient clé :</h3>
        <% if @main_ingredient.present? %>
          <h3 class="form-label text-size-regular color-green ms-2"><%= @main_ingredient.capitalize %></h3>
        <% else %>
          <h3 class="form-label text-size-regular color-green ms-2">Aucun</h3>
        <% end %>
      </div>
    </div>
    <div class="tag-wrapper">
      <% if @selected_tags.any? %>
        <% @selected_tags.each do |tag| %>
          <div class="tag-item tag-label">
            <%= tag.name %>
          </div>
          <% end %>
      <% end %>
    </div>
    <div class="results-wrapper">
      <h2 class="form-label text-size-regular text-weight-semibold mb-2">RESULTATS DE RECHERCHE :</h2>
      <% @recipes.each do |recipe| %>
        <strong><%= link_to "#{recipe.title.upcase} <i class='fa-solid fa-arrow-right'></i>".html_safe, recipe_path(recipe, return_to: request.fullpath), class: "recipe-link" %></strong>
      <% end %>
      <% @other_recipes.each do |recipe| %>
        <%= link_to "#{recipe.title.upcase} <i class='fa-solid fa-arrow-right'></i>".html_safe, recipe_path(recipe, return_to: request.fullpath), class: "recipe-link" %>
      <% end %>
    </div>
    <div class="return-wrapper">
      <%= link_to "Nouvelle recherche", categories_path, class:"return-link" %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="full-screen">
  <div class="container-custom">
      <%= form_with model: @recipe, url:recipes_path, method: :post, local: true, data: { turbo: false }, multipart: true do |f|  %>
        <div class="input-wrapper-low-padding input-wrapper-title">
          <label for="title" class="d-none">Titre</label>
          <%= f.text_field :title, placeholder: "Titre", class: "input-field input-uppercase title-placeholder" %>
        </div>
        <div class="d-flex flex-column align-items-center">
          <hr class="thick-line">
        </div>
        <div class="d-flex flex-column justify-content-start">
          <div class="input-wrapper-low-padding">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Catégorie* : </h3></div>
            <label for="category" class="d-none">Catégorie</label>
            <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), prompt: "", class: "input-field text-size-small input-uppercase category-placeholder" %>
          </div>
          <div class="input-wrapper-low-padding">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Ingrédient clé* : </h3></div>
            <label for="main_ingredient" class="d-none">Ingredient clé</label>
            <%= f.text_field :main_ingredient, placeholder: "Carotte", class: "input-field text-size-small input-uppercase lowercase-placeholder" %>
          </div>
          <div class="input-wrapper-column">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Autres ingrédients: </h3></div>
            <label for="recipe_ingredients" class="d-none">Autres ingrédients</label>
            <div class="input-container">
              <%= f.text_field :recipe_ingredients, value: nil, placeholder: "oignon, sauce soja, gingembre", class: "input-field text-size-small input-uppercase" %>
            </div>
          </div>
          <div class="text-start padding-left-custom">
            <h3 class="form-label text-size-regular text-start padding-left-add">Tags (cliquez pour sélectionner) : </h3>
          </div>
          <div class="tag-wrapper my-2">
            <% Tag.all.each do |tag| %>
              <div class="tag-item">
                <%= check_box_tag "tags[]", tag.id, params[:tags]&.include?(tag.id.to_s), id: "tag_#{tag.id}", class: "tag-checkbox" %>
                <%= label_tag "tag_#{tag.id}", tag.name, class: "tag-label" %>
              </div>
              <% end %>
          </div>
          <div class="input-wrapper-low-padding">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">URL : </h3></div>
            <label for="source_url" class="d-none">URL</label>
            <%= f.text_field :source_url, placeholder: "https://wwww....", class: "input-field text-size-small lowercase-placeholder" %>
          </div>
          <div class="input-wrapper-low-padding">
            <div class="d-flex justify-content-center align-items-center me-2"><h3 class="form-label text-size-regular">Photos : </h3></div>
            <label for="recipe_images" class="form-label d-none">Upload Images</label>
            <%= f.file_field :images, multiple: true, accept: "image/*", class: "input-field text-size-small lowercase-placeholder" %>
          </div>
        </div>
        <div class="d-flex justify-content-center mt-2">
          <%= f.submit "ENREGISTRER", class: "button-main" %>
        </div>
      <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="full-screen" data-controller="modal">
  <div class="container-custom">
    <% if params[:return_to].present? %>
      <div class="close-button">
        <%= link_to content_tag(:i, "", class: "fa-solid fa-xmark"), params[:return_to], class: "close-link" %>
      </div>
    <% else %>
      <div class="close-button">
        <%= link_to content_tag(:i, "", class: "fa-solid fa-xmark"), recipes_path, class: "close-link" %>
      </div>
    <% end %>
    <h1 class="text-center"><%= @recipe.title.capitalize %></h1>
    <hr class="thick-line">
    <div class="input-wrapper py-1 mt-1 d-flex flex-row justify-content-between">
      <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="form-label text-size-regular">Catégorie :</h3>
          <% if @selected_category.present? %>
            <h3 class="form-label text-size-regular color-green ms-2">
            <%= @selected_category.name.upcase %>
          </h3>
        <% else %>
          <h3 class="form-label text-size-regular color-green ms-2">Non renseignée</h3>
        <% end %>
      </div>
      <div class="pb-1">
        <%= link_to "Modifier la recette", edit_recipe_path(@recipe, return_to: params[:return_to]), class:"edit-link" %>
      </div>
    </div>
    <div class="input-wrapper py-1">
      <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="form-label text-size-regular">Ingrédient clé :</h3>
        <% if @main_ingredient.present? %>
          <h3 class="form-label text-size-regular color-green ms-2"><%= @main_ingredient.upcase %></h3>
        <% else %>
          <h3 class="form-label text-size-regular color-green ms-2">Non renseigné</h3>
        <% end %>
      </div>
    </div>
    <div class="input-wrapper py-1">
      <div class="d-flex flex-row justify-content-start align-items-center flex-wrap">
        <h3 class="form-label text-size-regular me-2">Autres ingrédients :</h3>
        <% if @ingredients_list.present? %>
          <% @ingredients_list.each_with_index do |ingredient, index| %>
            <span class="ingredients-list-wrapper form-label text-size-regular color-green">
              <%= ingredient.name.capitalize %><%= ",".html_safe if index < @ingredients_list.length - 1 %>&nbsp;
            </span>
          <% end %>
        <% else %>
          <h3 class="form-label text-size-regular color-green ms-2">Non renseignés</h3>
        <% end %>
      </div>
    </div>
    <div class="tag-wrapper">
      <% if @recipe.tags.any? %>
        <% @recipe.tags.each do |tag| %>
          <div class="tag-item tag-label">
            <%= tag.name %>
          </div>
        <% end %>
      <% end %>
    </div>
    <% if @recipe.images.attached? %>
      <div class="source-wrapper">
        <div class="image-holder">
          <%= image_tag url_for(@recipe.images.first), class: "recipe-image" %>
        </div>
      </div>
      <div class="d-flex justify-content-center mt-3">
        <button type="button" class="button-main" data-action="click->modal#open">Voir la recette</button>
      </div>
    <% elsif @recipe.source_url.present? %>
      <div class="source-wrapper">
        <div class="image-holder">
          <p>Recette en ligne</p>
        </div>
      </div>
      <div class="d-flex justify-content-center mt-3">
        <%= link_to "Voir la recette", @recipe.source_url, target: "_blank", class: "button-main" %>
      </div>
    <% else %>
      <p class="error-message">Recette indisponible</p>
    <% end %>

    <!-- Modal for images -->
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-fullscreen-lg-down">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="imageModalLabel"><%= "#{pluralize(@recipe.images.count, 'photo')}" %></h5>
            <button type="button" class="btn-close" data-action="click->modal#close" aria-label="Close"></button>
          </div>
          <div class="modal-body d-flex flex-column justify-content-between">
            <div id="imageSlider" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner" data-modal-target="imageContainer">
                <% @recipe.images.each_with_index do |image, index| %>
                  <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
                    <img src="<%= url_for(image) %>" class="d-block w-100" alt="Image <%= index + 1 %>" style="object-fit: contain; max-height: 75vh;">
                  </div>
                <% end %>
              </div>
            </div>
            <div class="d-flex flex-row justify-content-between mt-3">
              <button class="carousel-control-prev" type="button" data-bs-target="#imageSlider" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Précédente</span>
              </button>
              <button class="carousel-control-next ms-3" type="button" data-bs-target="#imageSlider" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Prochaine</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>